version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Raudbjorn"

  # Enable version updates for npm in service directory
  - package-ecosystem: "npm"
    directory: "/service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Raudbjorn"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Raudbjorn"