version: '3.9'

# Production compose file using pre-built images from GitHub Container Registry
# Usage: docker compose -f compose.production.yaml up -d

networks:
  pds:
    driver: bridge

services:
  nginx:
    container_name: pds-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pds
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nginx/pds-configured.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: /var/www/certbot
        target: /var/www/certbot
        read_only: true
    networks:
      - pds

  pds:
    container_name: pds
    # Use the pre-built image from GitHub Container Registry
    image: ghcr.io/raudbjorn/pds:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds
        target: /pds
    env_file:
      - /pds/pds.env
    networks:
      - pds
    # Expose port for nginx to connect to
    expose:
      - "3000"
    # Optional: Enable tracing in production
    # environment:
    #   - NODE_ENV=production
    #   - DD_ENV=production
    #   - DD_SERVICE=pds
    #   - DD_VERSION=latest